// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD506UOmv58bsN_Oc_RjSxGoH8XeF8qmyk',
    appId: '1:1068003107311:web:52469046ad4a5c2cb3d61a',
    messagingSenderId: '1068003107311',
    projectId: 'flutter-maps-project-460412',
    authDomain: 'flutter-maps-project-460412.firebaseapp.com',
    storageBucket: 'flutter-maps-project-460412.firebasestorage.app',
    measurementId: 'G-EBM0E9SBKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCe5zVgM_ANn7KsNicVMfPox4Ox84ypM',
    appId: '1:1068003107311:android:c1ab9c67ab35a204b3d61a',
    messagingSenderId: '1068003107311',
    projectId: 'flutter-maps-project-460412',
    storageBucket: 'flutter-maps-project-460412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1_JlvzIcU8GVe-eJvTGhJeSz6EHcKLY',
    appId: '1:1068003107311:ios:8c737ae6151ac8c0b3d61a',
    messagingSenderId: '1068003107311',
    projectId: 'flutter-maps-project-460412',
    storageBucket: 'flutter-maps-project-460412.firebasestorage.app',
    iosBundleId: 'com.example.onTheGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1_JlvzIcU8GVe-eJvTGhJeSz6EHcKLY',
    appId: '1:1068003107311:ios:8c737ae6151ac8c0b3d61a',
    messagingSenderId: '1068003107311',
    projectId: 'flutter-maps-project-460412',
    storageBucket: 'flutter-maps-project-460412.firebasestorage.app',
    iosBundleId: 'com.example.onTheGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD506UOmv58bsN_Oc_RjSxGoH8XeF8qmyk',
    appId: '1:1068003107311:web:f422a6ca6ebada5eb3d61a',
    messagingSenderId: '1068003107311',
    projectId: 'flutter-maps-project-460412',
    authDomain: 'flutter-maps-project-460412.firebaseapp.com',
    storageBucket: 'flutter-maps-project-460412.firebasestorage.app',
    measurementId: 'G-3X371MGRTZ',
  );
}
